# Generated by Django 3.1.7 on 2021-06-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactforms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForms',
            new_name='ContactForm',
        ),
    ]
