# Generated by Django 3.1.7 on 2021-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
